"""V4.1 entry-quality research configuration."""

import os

V41_ENTRY_WAIT_HOURS = int(os.getenv("V41_ENTRY_WAIT_HOURS", "8"))
V41_ZONE_BUFFER_ATR = float(os.getenv("V41_ZONE_BUFFER_ATR", "0.18"))
V41_STOP_BUFFER_ATR = float(os.getenv("V41_STOP_BUFFER_ATR", "0.12"))
V41_MAX_CHASE_ATR = float(os.getenv("V41_MAX_CHASE_ATR", "0.30"))
V41_MIN_SUPPORT_ROOM_R = float(os.getenv("V41_MIN_SUPPORT_ROOM_R", "2.0"))
V41_MAX_STOP_PCT = float(os.getenv("V41_MAX_STOP_PCT", "6.0"))
V41_CONFIRM_MIN_SCORE = int(os.getenv("V41_CONFIRM_MIN_SCORE", "2"))

# Zone quality / invalidation.
V41_MAX_SUPPLY_PRIOR_TOUCHES = int(os.getenv("V41_MAX_SUPPLY_PRIOR_TOUCHES", "1"))
V41_MAX_SWEEP_AGE_1H_BARS = int(os.getenv("V41_MAX_SWEEP_AGE_1H_BARS", "4"))
V41_MAX_BREAKDOWN_AGE_1H_BARS = int(os.getenv("V41_MAX_BREAKDOWN_AGE_1H_BARS", "12"))
V41_ZONE_INVALIDATION_ATR = float(os.getenv("V41_ZONE_INVALIDATION_ATR", "0.12"))
V41_UNKNOWN_SUPPORT_POLICY = os.getenv("V41_UNKNOWN_SUPPORT_POLICY", "REJECT").upper()

# 15m structure-shift confirmation.
V41_BOS_LOOKBACK_BARS = int(os.getenv("V41_BOS_LOOKBACK_BARS", "8"))
V41_BOS_WINDOW_BARS = int(os.getenv("V41_BOS_WINDOW_BARS", "8"))
V41_RETEST_WINDOW_BARS = int(os.getenv("V41_RETEST_WINDOW_BARS", "6"))
V41_BOS_BUFFER_ATR1H = float(os.getenv("V41_BOS_BUFFER_ATR1H", "0.03"))
V41_RETEST_TOLERANCE_ATR1H = float(os.getenv("V41_RETEST_TOLERANCE_ATR1H", "0.08"))
V41_RECLAIM_INVALIDATION_ATR1H = float(os.getenv("V41_RECLAIM_INVALIDATION_ATR1H", "0.12"))

V41_POST_SL_HOURS = int(os.getenv("V41_POST_SL_HOURS", "72"))
V41_FOLLOWTHROUGH_HOURS = (1, 4, 12, 24)
