"""V4.2.3 continuation-first discretionary Short filter."""

import os

# Scanner visibility / ranking.
V423_MIN_EMIT_SCORE = float(os.getenv("V423_MIN_EMIT_SCORE", "34"))
V423_MIN_SHORT_NOW_SCORE = float(os.getenv("V423_MIN_SHORT_NOW_SCORE", "38"))

# Continuation structure.
V423_BREAKDOWN_MAX_AGE_1H = int(os.getenv("V423_BREAKDOWN_MAX_AGE_1H", "12"))
V423_MIN_BREAK_DEPARTURE_ATR = float(os.getenv("V423_MIN_BREAK_DEPARTURE_ATR", "0.35"))
V423_MIN_BREAK_BODY_ATR = float(os.getenv("V423_MIN_BREAK_BODY_ATR", "0.30"))
V423_RETEST_TOUCH_ATR = float(os.getenv("V423_RETEST_TOUCH_ATR", "0.20"))
V423_RETEST_CLOSE_BELOW_ATR = float(os.getenv("V423_RETEST_CLOSE_BELOW_ATR", "0.03"))
V423_RECLAIM_INVALIDATION_ATR = float(os.getenv("V423_RECLAIM_INVALIDATION_ATR", "0.12"))
V423_MAX_RETEST_ACCEPTANCE_BARS = int(os.getenv("V423_MAX_RETEST_ACCEPTANCE_BARS", "3"))
V423_MIN_REJECTION_UPPER_WICK_RATIO = float(os.getenv("V423_MIN_REJECTION_UPPER_WICK_RATIO", "0.20"))
V423_MAX_BULLISH_RETEST_BODY_ATR = float(os.getenv("V423_MAX_BULLISH_RETEST_BODY_ATR", "0.45"))

# False-retest / squeeze risk.
V423_MAX_MARKET_BOUNCE_4H_PCT = float(os.getenv("V423_MAX_MARKET_BOUNCE_4H_PCT", "1.25"))
V423_MAX_RELATIVE_RECOVERY_1H_PCT = float(os.getenv("V423_MAX_RELATIVE_RECOVERY_1H_PCT", "1.00"))
V423_MAX_RELATIVE_RECOVERY_3H_PCT = float(os.getenv("V423_MAX_RELATIVE_RECOVERY_3H_PCT", "1.75"))
V423_MAX_REBOUND_FROM_BREAK_LOW_ATR = float(os.getenv("V423_MAX_REBOUND_FROM_BREAK_LOW_ATR", "1.50"))
V423_MAX_SQUEEZE_RISK = float(os.getenv("V423_MAX_SQUEEZE_RISK", "6.0"))

# Anti-bottom.
V423_MAX_ANTI_BOTTOM_FOR_SHORT_NOW = float(os.getenv("V423_MAX_ANTI_BOTTOM_FOR_SHORT_NOW", "10.0"))
V423_RECENT_LOW_BLOCK_ATR = float(os.getenv("V423_RECENT_LOW_BLOCK_ATR", "0.30"))
V423_SUPPORT_BLOCK_ATR = float(os.getenv("V423_SUPPORT_BLOCK_ATR", "0.70"))

# Reference levels only.
V423_REFERENCE_STOP_BUFFER_ATR = float(os.getenv("V423_REFERENCE_STOP_BUFFER_ATR", "0.18"))
V423_SLIPPAGE_BPS_REFERENCE = float(os.getenv("V423_SLIPPAGE_BPS_REFERENCE", "6"))

V423_DIRECTION_HOURS = (1, 4, 12)
V423_FIRST_MOVE_ATR = float(os.getenv("V423_FIRST_MOVE_ATR", "0.50"))
V423_FIRST_MOVE_WINDOW_HOURS = int(os.getenv("V423_FIRST_MOVE_WINDOW_HOURS", "12"))
